"use client";

import { useState } from "react";
import { money, products } from "../data";

const nav = [
  ["/admin","Vue d’ensemble","⌂"],["/admin/produits","Produits","◇"],["/admin/stocks","Stocks","▦"],["/admin/ventes","Ventes","↗"],["/admin/clientes","Clientes","○"],["/admin/avis","Avis","☆"],["/admin/parametres","Paramètres","⚙"],
];
const sales = [
  { id:"JV-1048", client:"Aminata K.", product:"Star", channel:"WhatsApp", total:17000, status:"Confirmée", date:"14 juil., 10:22" },
  { id:"JV-1047", client:"Fatou S.", product:"Magic", channel:"Snapchat", total:8500, status:"Préparée", date:"14 juil., 09:08" },
  { id:"JV-1046", client:"Mariama O.", product:"Sienna", channel:"WhatsApp", total:9000, status:"Nouvelle", date:"13 juil., 18:41" },
  { id:"JV-1045", client:"Aïcha T.", product:"Star", channel:"WhatsApp", total:8500, status:"Livrée", date:"13 juil., 15:12" },
];

function AdminShell({ active, children }: { active:string; children:React.ReactNode }) {
  return <div className="admin-layout"><aside className="admin-sidebar"><a className="admin-logo" href="/">JAWNAH<span>admin studio</span></a><nav>{nav.map(([href,label,icon]) => <a key={href} className={active === href ? "active" : ""} href={href}><i>{icon}</i>{label}</a>)}</nav><div className="admin-user"><span>JA</span><div><b>Jawna Admin</b><small>Administratrice</small></div></div></aside><div className="admin-main"><header><div><span className="admin-mobile-logo">JAWNAH</span><small>Administration</small></div><div><button aria-label="Notifications">♢<i>3</i></button><a href="/">Voir la boutique ↗</a></div></header>{children}</div></div>;
}

function Stat({ label, value, note, tone }: { label:string; value:string; note:string; tone?:string }) { return <div className={`admin-stat ${tone || ""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function SalesTable() { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Commande</th><th>Cliente</th><th>Produit</th><th>Canal</th><th>Montant</th><th>Statut</th></tr></thead><tbody>{sales.map(s => <tr key={s.id}><td><b>{s.id}</b><small>{s.date}</small></td><td>{s.client}</td><td>{s.product}</td><td><span className={`channel-pill ${s.channel.toLowerCase()}`}>{s.channel}</span></td><td>{money(s.total)}</td><td><span className={`status ${s.status.toLowerCase().replace("é","e")}`}>{s.status}</span></td></tr>)}</tbody></table></div>; }

export function AdminDashboard() { return <AdminShell active="/admin"><div className="admin-page-head"><div><p>Bonjour Jawna ✦</p><h1>Vue d’ensemble</h1></div><div className="admin-period"><button>Aujourd’hui</button><button className="active">7 derniers jours</button><button>Ce mois</button></div></div><div className="admin-stats"><Stat label="Chiffre d’affaires" value="184 500 F" note="↑ 18,4 % cette semaine" tone="featured"/><Stat label="Ventes" value="24" note="↑ 6 vs semaine passée"/><Stat label="Produits vendus" value="31" note="Panier moyen : 1,3"/><Stat label="Clientes" value="128" note="+ 9 nouvelles"/></div><div className="admin-grid"><section className="admin-card chart-card"><header><div><small>Performances</small><h2>Évolution des ventes</h2></div><strong>184 500 F CFA</strong></header><div className="bars">{[38,55,44,72,63,88,78].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"][i]}</small></div>)}</div></section><section className="admin-card channel-card"><small>Canaux</small><h2>Origine des ventes</h2><div className="donut"><div><strong>24</strong><span>ventes</span></div></div><div className="legend"><span><i/>WhatsApp <b>67%</b></span><span><i/>Snapchat <b>33%</b></span></div></section></div><div className="admin-grid lower"><section className="admin-card"><header><div><small>Activité récente</small><h2>Dernières ventes</h2></div><a href="/admin/ventes">Tout afficher →</a></header><SalesTable/></section><section className="admin-card stock-alert"><small>À surveiller</small><h2>Alertes stock</h2>{products.map(p => <div key={p.id}><img src={p.image} alt=""/><span><b>{p.shade}</b><small>{p.stock < 8 ? "Stock faible" : "Disponible"}</small></span><strong className={p.stock < 8 ? "warn" : ""}>{p.stock}</strong></div>)}<a href="/admin/stocks">Gérer les stocks →</a></section></div></AdminShell>; }

export function AdminProducts() { const [notice,setNotice]=useState(false); return <AdminShell active="/admin/produits"><div className="admin-page-head"><div><p>Catalogue</p><h1>Produits</h1></div><button className="admin-primary" onClick={()=>setNotice(true)}>+ Ajouter un produit</button></div>{notice && <div className="admin-notice">Le formulaire de création est prêt à être relié à la base JAWNAH. <button onClick={()=>setNotice(false)}>×</button></div>}<section className="admin-card"><div className="table-tools"><input placeholder="Rechercher un produit…"/><select><option>Tous les statuts</option><option>Actif</option><option>Archivé</option></select></div><div className="admin-table-wrap"><table className="admin-table product-table"><thead><tr><th>Produit</th><th>Catégorie</th><th>Prix</th><th>Stock</th><th>Badge</th><th>Statut</th><th/></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><div className="table-product"><img src={p.image} alt=""/><span><b>{p.name}</b><small>Teinte {p.shade}</small></span></div></td><td>{p.category}</td><td>{money(p.price)}</td><td><b className={p.stock<8?"warn":""}>{p.stock}</b></td><td>{p.badge}</td><td><span className="status livree">Actif</span></td><td><button className="dots">•••</button></td></tr>)}</tbody></table></div></section></AdminShell>; }

export function AdminStocks() { const [stocks,setStocks]=useState(Object.fromEntries(products.map(p=>[p.id,p.stock]))); return <AdminShell active="/admin/stocks"><div className="admin-page-head"><div><p>Inventaire</p><h1>Stocks</h1></div><button className="admin-primary">+ Enregistrer un mouvement</button></div><div className="admin-stats compact"><Stat label="Stock total" value={String(Object.values(stocks).reduce((a,b)=>a+Number(b),0))} note="Toutes les unités"/><Stat label="Disponibles" value="3" note="Produits actifs"/><Stat label="Stock faible" value="1" note="Sienna sous le seuil" tone="warning"/><Stat label="Rupture" value="0" note="Aucun produit"/></div><section className="admin-card"><header><div><small>Mise à jour rapide</small><h2>Quantités disponibles</h2></div></header><div className="stock-list">{products.map(p=><div key={p.id}><img src={p.image} alt=""/><span><b>{p.name}</b><small>Seuil faible : 8</small></span><div className="stock-meter"><i style={{width:`${Math.min(100,Number(stocks[p.id])*5)}%`}}/></div><label><input type="number" min="0" value={stocks[p.id]} onChange={e=>setStocks({...stocks,[p.id]:Number(e.target.value)})}/> unités</label></div>)}</div></section></AdminShell>; }

export function AdminSales() { return <AdminShell active="/admin/ventes"><div className="admin-page-head"><div><p>Commandes sociales</p><h1>Ventes</h1></div><button className="admin-primary">+ Enregistrer une vente</button></div><div className="admin-stats compact"><Stat label="Nouvelles" value="4" note="À confirmer"/><Stat label="À préparer" value="6" note="Confirmées"/><Stat label="Livrées ce mois" value="38" note="↑ 12 %"/><Stat label="Chiffre d’affaires" value="356 000 F" note="Ce mois-ci" tone="featured"/></div><section className="admin-card"><div className="table-tools"><input placeholder="Rechercher une vente…"/><select><option>Tous les canaux</option><option>WhatsApp</option><option>Snapchat</option></select><select><option>Tous les statuts</option><option>Nouvelle</option><option>Confirmée</option><option>Livrée</option></select></div><SalesTable/></section></AdminShell>; }

export function AdminSimple({ type }: { type:"clientes"|"avis"|"parametres" }) { const active=`/admin/${type}`; const [saved,setSaved]=useState(false); const title={clientes:"Clientes",avis:"Avis clientes",parametres:"Paramètres"}[type]; return <AdminShell active={active}><div className="admin-page-head"><div><p>Gestion</p><h1>{title}</h1></div>{type!=="clientes"&&<button className="admin-primary" onClick={()=>setSaved(true)}>{type==="avis"?"+ Ajouter un avis":"Enregistrer"}</button>}</div>{saved&&<div className="admin-notice">Modifications enregistrées dans cette démonstration. <button onClick={()=>setSaved(false)}>×</button></div>}{type==="clientes"&&<section className="admin-card"><div className="admin-list-rows">{["Aminata Koné","Fatou Sawadogo","Mariama Ouédraogo","Aïcha Traoré"].map((n,i)=><div key={n}><span>{n.split(" ").map(x=>x[0]).join("")}</span><b>{n}</b><small>{[5,3,2,4][i]} favoris</small><small>{[2,1,1,3][i]} commandes</small><button>Voir le profil →</button></div>)}</div></section>}{type==="avis"&&<section className="admin-card"><div className="admin-list-rows reviews-admin">{["Star illumine sans en faire trop.","Le rouge Sienna est intense et élégant.","Magic donne exactement l’effet recherché."].map((text,i)=><div key={text}><span>★★★★★</span><b>{["Aminata","Salimata","Fatou"][i]}</b><small>{text}</small><button>•••</button></div>)}</div></section>}{type==="parametres"&&<section className="settings-grid"><div className="admin-card settings-form"><small>Canaux de commande</small><h2>WhatsApp & Snapchat</h2><label>Numéro WhatsApp<input defaultValue="22670000000"/></label><label>Nom d’utilisateur Snapchat<input defaultValue="jawna.gloss"/></label><label>Nom d’utilisateur Instagram<input defaultValue="jawna.gloss"/></label></div><div className="admin-card settings-form"><small>Boutique</small><h2>Informations générales</h2><label>Nom de la marque<input defaultValue="JAWNAH"/></label><label>Zone de livraison<input defaultValue="Ouagadougou et Burkina Faso"/></label><label>Seuil de stock faible<input type="number" defaultValue="8"/></label></div></section>}</AdminShell>; }
