"use client";

import { useEffect, useState } from "react";
import { money, Product, settings, whatsappUrl } from "../data";
import { OrderModal } from "./store-front";
import { readFavorites } from "./product-card";

export function ProductDetail({ product }: { product: Product }) {
  const [favorite, setFavorite] = useState(false); const [order, setOrder] = useState<Product | null>(null); const [angle, setAngle] = useState(0); const [copied, setCopied] = useState(false);
  useEffect(() => setFavorite(readFavorites().includes(product.id)), [product.id]);
  const toggle = () => { const list = readFavorites(); const next = list.includes(product.id) ? list.filter(id => id !== product.id) : [...list, product.id]; localStorage.setItem("jawna-favorites", JSON.stringify(next)); setFavorite(next.includes(product.id)); };
  return <main className="product-detail"><section className="detail-grid"><div className="detail-gallery" style={{ "--tint": product.color } as React.CSSProperties}><div className="detail-main"><span className="badge">{product.badge}</span><img src={product.image} alt={`Gloss JAWNAH ${product.shade}`} style={{ transform:`rotateY(${angle}deg)` }}/><input type="range" min="-12" max="12" value={angle} onChange={e => setAngle(Number(e.target.value))} aria-label="Faire pivoter le produit"/><small>← Faites pivoter le gloss →</small></div><div className="detail-thumbs"><button><img src={product.image} alt="Vue du gloss"/></button><button className="texture-swatch" style={{ background:product.color }} aria-label="Aperçu de la texture"/><button className="video-thumb" onClick={() => document.getElementById("ritual-video")?.scrollIntoView()} aria-label="Voir la vidéo">▶</button></div></div>
      <div className="product-detail-copy"><div className="eyebrow">JAWNAH · Lip gloss</div><h1>{product.shade}</h1><div className="detail-price">{money(product.price)}</div><p className="detail-lead">{product.summary} Une formule confortable qui lisse visuellement les lèvres et dépose un éclat précis, sans sensation lourde.</p><div className="detail-facts"><div><span>Fini</span><b>{product.category === "Rouge" ? "Laqué miroir" : "Brillant lumière"}</b></div><div><span>Texture</span><b>Légère & non collante</b></div><div><span>Teinte</span><b>{product.shade}</b></div><div><span>Disponibilité</span><b className={product.stock < 8 ? "low-stock" : "in-stock"}>{product.stock} en stock</b></div></div>
      <div className="detail-actions"><button className="button button-dark" onClick={() => setOrder(product)}>Commander</button><button className={`detail-heart ${favorite ? "active" : ""}`} onClick={toggle}>{favorite ? "♥" : "♡"}<span>{favorite ? "Dans vos favoris" : "Ajouter aux favoris"}</span></button></div>
      <div className="direct-channels"><a href={whatsappUrl(product)} target="_blank" rel="noreferrer">Commander sur WhatsApp <span>↗</span></a><button onClick={async () => { await navigator.clipboard?.writeText(`${product.name} — teinte ${product.shade}`); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }}>Copier le produit pour Snapchat <span>{copied ? "Copié ✓" : "⧉"}</span></button><a href={`https://www.snapchat.com/add/${settings.snapchat}`} target="_blank" rel="noreferrer">Ouvrir Snapchat <span>↗</span></a></div>
      <details open><summary>Conseils d’utilisation</summary><p>Appliquez au centre des lèvres puis étirez vers les commissures. Portez-le seul pour un fini naturel ou sur un crayon pour un effet plus structuré.</p></details><details><summary>Livraison & commande</summary><p>La commande est confirmée avec l’équipe JAWNAH sur WhatsApp ou Snapchat. Aucun paiement n’est réalisé sur le site.</p></details></div></section>
    <section className="detail-video" id="ritual-video"><video autoPlay muted loop playsInline preload="metadata"><source src="/jawna-video.mp4" type="video/mp4"/></video><div><div className="eyebrow light-text">En mouvement</div><h2>L’éclat, au plus près.</h2><p>Une application souple et un fini lumineux dès le premier passage.</p></div></section><OrderModal product={order} onClose={() => setOrder(null)}/></main>;
}
